# src/settings.py
"""
Global settings for the Portfolio Analyzer.

This file centralizes:
  - I/O locations and default data period
  - Frequency, missing-data handling, and rebalancing cadence
  - Investment styles and defaults for rolling analysis
  - Series (data) resolution policy used by the loader
  - Portfolio compositions used by the simulator
  - Leveraged ETF simulation defaults
  - Tax treatment for rebalancing gains

IMPORTANT
---------
- All paths are resolved relative to the project root directory (the parent
  directory that contains 'rollpath').
- The loader (src/data_loader.py) strictly respects the file/patterns listed
  in SERIES_SPECS. It **does not** attempt to "guess" missing names.
- The tax model (TAX_RATE) is applied **only at rebalancing points** and only
  to the **realized gains** generated by selling appreciated positions during
  the rebalance. There is no tax for 'rebalance = none'.

TAX MODEL OVERVIEW
------------------
At each rebalance boundary:
  1) Winners (overweight assets) are partially sold down to target weights.
  2) The realized gains from the sold portions are taxed at TAX_RATE.
     - We assume average cost basis (i.e., proportional basis) within each asset.
     - The tax is funded from the portfolio value at rebalance. We solve for
       the after-tax portfolio value self-consistently so that weights end at
       the target after tax.
  3) Between rebalances, no taxes are applied.

This is an economically reasonable approximation for rebalancing taxation.
It is **not** a lot-specific realization or wash-sale model.
"""

from datetime import datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Directories
# ---------------------------------------------------------------------------
current_path = Path(__file__).resolve()
project_keyword = "rollpath"
while project_keyword not in current_path.name.lower():
    if current_path.parent == current_path:
        raise ValueError(f"'{project_keyword}' directory could not be found")
    current_path = current_path.parent

BASE_DIR = current_path
DATA_DIR = BASE_DIR / "data"
# OUTPUT_DIR = BASE_DIR / "output" / Path(datetime.now().strftime("%Y%m%d_%H%M"))
OUTPUT_DIR = BASE_DIR / "output"

# ---------------------------------------------------------------------------
# Global data window and frequency
# ---------------------------------------------------------------------------
# Default analysis date range (inclusive). You can override from CLI if needed.
# START_DATE = "1928-01-01" # SPXL/SSO
START_DATE = "1985-10-01" # TQQQ/QLD
END_DATE = datetime.today().strftime("%Y-%m-%d")

# Input sampling frequency used by the loader ('daily'|'monthly'|'yearly')
DATA_FREQ = "daily"

# How to fill missing values before resampling:
#   'ffill' = forward-fill
#   'bfill' = back-fill
#   'both'  = forward then back fill
#   any other/None = no fill
MISSING_DATA_STRATEGY = "both"

# Rebalancing cadence for portfolio simulation:
#   'none'         : buy-and-hold (no rebalancing → no realized tax)
#   'every_period' : rebalance at each row (e.g., each trading day)
#   'monthly'      : rebalance at calendar month boundaries
#   'yearly'       : rebalance at calendar year boundaries
#   'yearly_X'     : rebalance every X years (e.g., 'yearly_3' = every 3 years)
REBALANCE_FREQ = "yearly"

# Risk-free rate (annualized) for Sharpe computations in the rolling metrics
RISK_FREE_RATE = 0.033

# ---------------------------------------------------------------------------
# Rolling window settings (used by main.py rolling analysis)
# ---------------------------------------------------------------------------
# Which investment windows to evaluate by default (e.g., 10, 20, 30 years)
INVESTMENT_PERIOD_VALUES = [i for i in range(5, 31, 5)]
# Window unit: 'days' | 'months' | 'years'
INVESTMENT_PERIOD_UNIT = "years"

# DCA or LumpSum rolling evaluation
#   'lump_sum' : one-shot investment at the start of each rolling window
#   'dca'      : contribute 'DCA_AMOUNT' each period inside the window plus
#                'INITIAL_CAPITAL' at the first period of the window
INVESTMENT_STYLE = "dca"
INITIAL_CAPITAL = 0
DCA_AMOUNT = 100_000.0
# ---------------------------------------------------------------------------
# Input file patterns
# ---------------------------------------------------------------------------
# Patterns are evaluated inside DATA_DIR unless an absolute path is provided.
#
# Files whose names contain any of the substrings in EXCLUDE_FILENAME_SUBSTRINGS
# are ignored when "latest file" resolution is performed.
EXCLUDE_FILENAME_SUBSTRINGS = ("sim",)

INDEX_FILE_GLOBS = {
    "SP500": "^spx_d_*.csv",
    "NDX": "*ndx_d*.csv",
}

ACTUAL_ETF_FILE_GLOBS = {
    "SPXL": "*spxl_d_*.csv",
    "SSO": "*sso_d_*.csv",
    "TQQQ": "*tqqq_d_*.csv",
    "QLD": "*qld_d_*.csv",
}

RAW_DATA_FILES = {
    "sp500_dividend_monthly": "raw/SPX Dividend Yield by Month_*.csv",
    "tbill_1920_1934_monthly": "raw/Yields on Short-Term United States Securities*.csv",
    "tb3ms_1934_now_monthly": "raw/*TB3MS*.csv",
}

# ---------------------------------------------------------------------------
# Series resolution for the loader
# ---------------------------------------------------------------------------
# Keys are the logical series names used throughout the app; values are exact
# filenames or glob patterns under DATA_DIR. The loader always respects these
# fully—no implicit renaming or guessing.
SERIES_SPECS = {
    "SP500_TR": "^SPX_*_daily_TR.csv",  # S&P 500 Total Return (daily)
    "NDX_TR": "*ndx_d*.csv",
    "SSO_2x_TR": "^sso_simulated_d_TR_*%cost*.csv",  # 2x TR simulation (daily)
    "SPXL_3x_TR": "^spxl_simulated_d_TR_*%cost*.csv",  # 3x TR simulation (daily)
    "TQQQ_3x_TR": "^tqqq_simulated_d_TR_*.csv",
    "QLD_2x_TR": "^qld_simulated_d_TR_*.csv",
}

# ---------------------------------------------------------------------------
# Portfolio definitions
# ---------------------------------------------------------------------------
# Each portfolio maps constituent series (above) to weights.
# Weights are automatically normalized if they do not sum exactly to 1.0.
PORTFOLIOS = {
    # "S&P500": {"SP500_TR": 1.0},
    "Nasdaq-100": {"NDX_TR": 1.0},
    # "sim_SSO": {"SSO_2x_TR": 1.0},
    # "sim_SPXL": {"SPXL_3x_TR": 1.0},
    "sim_QLD": {"QLD_2x_TR": 1.0},
    "sim_TQQQ": {"TQQQ_3x_TR": 1.0},
    #
    # "S&P500 25/75 SSO": {"SP500_TR": 0.25, "SSO_2x_TR": 0.75},
    # "S&P500 50/50 SSO": {"SP500_TR": 0.5,  "SSO_2x_TR": 0.5},
    # "S&P500 75/25 SSO": {"SP500_TR": 0.75, "SSO_2x_TR": 0.25},
    #
    # "S&P500 25/75 SPXL": {"SP500_TR": 0.25, "SPXL_3x_TR": 0.75},
    # "S&P500 50/50 SPXL": {"SP500_TR": 0.5,  "SPXL_3x_TR": 0.5},
    # "S&P500 75/25 SPXL": {"SP500_TR": 0.75, "SPXL_3x_TR": 0.25},
    # "SPXL 50/Cash 50": {"SPXL_3x_TR": 0.50, "CASH": 0.50},  If you want cash in portoflio
}

# ---------------------------------------------------------------------------
# Leveraged ETF simulation defaults
# ---------------------------------------------------------------------------
# Models:
# - "dividend_carry":
#       r_sim = L * r_index + [L * div_y - (L - 1) * borrow] * dt - fee * dt
# - "constant_effective_carry":
#       r_sim = L * r_index + [carry - (L - 1) * borrow] * dt - fee * dt
#
# The constant_effective_carry model is intended for TQQQ / QLD total-return
# reconstruction when a long ^XNDX history or a long ^NDX dividend-yield history
# is unavailable.

COMMON_BORROW_ALPHA = 1.073577
COMMON_BORROW_BETA = 0.4522 / 100

INCLUDE_DIVIDENDS = True
BASE_FROM_INDEX = True

SIMULATION_SPECS = {
    "SPXL": {
        "model": "dividend_carry",
        "underlying": "SP500",
        "leverage": 3,
        "cost_annual": 0.01022,
        "borrow_alpha": 1.073577,
        "borrow_beta": 0.4543 / 100,
        "carry_annual": 0.0,
        "output_prefix": "^spxl_simulated_d",
    },
    "SSO": {
        "model": "dividend_carry",
        "underlying": "SP500",
        "leverage": 2,
        "cost_annual": 0.01004,
        "borrow_alpha": 1.044867,
        "borrow_beta": 0.4522 / 100,
        "carry_annual": 0.0,
        "output_prefix": "^sso_simulated_d",
    },
    "TQQQ": {
        "model": "constant_effective_carry",
        "underlying": "NDX",
        "leverage": 3,
        "cost_annual": 0.0097,
        "borrow_alpha": 1.345167,
        "borrow_beta": 0.001,
        "carry_annual": 0.02908374,
        "output_prefix": "^tqqq_simulated_d",
    },
    "QLD": {
        "model": "constant_effective_carry",
        "underlying": "NDX",
        "leverage": 2,
        "cost_annual": 0.0098,
        "borrow_alpha": 1.236665,
        "borrow_beta": 0.001,
        "carry_annual": 0.01579636,
        "output_prefix": "^qld_simulated_d",
    },
}

SIMULATION_DEFAULT_SYMBOLS = ["SPXL", "SSO", "TQQQ", "QLD"]

# ---------------------------------------------------------------------------
# Optimization defaults for leveraged ETF calibration
# ---------------------------------------------------------------------------
# Each symbol can define:
# - actual_glob: pattern for the live ETF history inside DATA_DIR
# - optimize_params: parameters to optimize
# - bounds: lower/upper bounds for each parameter
# - initial: initial guess for each parameter
#
# Supported optimizable parameters:
# - "borrow_alpha"
# - "borrow_beta"
# - "cost_annual"
# - "carry_annual"
OPTIMIZATION_DEFAULT_SYMBOLS = ["SPXL", "SSO", "TQQQ", "QLD"]
OPTIMIZATION_DEFAULT_LOSS = "mae"
OPTIMIZATION_DEFAULT_HUBER_DELTA = 1.0
OPTIMIZATION_DEFAULT_TRIM = 0.02
OPTIMIZATION_MAX_OUTER = 12
OPTIMIZATION_TOL = 1e-5
OPTIMIZATION_SAVE_BEST_SIM = True

OPTIMIZATION_SPECS = {
    "SPXL": {
        "actual_glob": ACTUAL_ETF_FILE_GLOBS["SPXL"],
        "optimize_params": ["borrow_alpha", "borrow_beta", "cost_annual"],
        "bounds": {
            "borrow_alpha": (0.80, 1.50),
            "borrow_beta": (0.0000, 0.0300),
            "cost_annual": (0.0080, 0.0500),
        },
        "initial": {
            "borrow_alpha": SIMULATION_SPECS["SPXL"]["borrow_alpha"],
            "borrow_beta": SIMULATION_SPECS["SPXL"]["borrow_beta"],
            "cost_annual": SIMULATION_SPECS["SPXL"]["cost_annual"],
        },
    },
    "SSO": {
        "actual_glob": ACTUAL_ETF_FILE_GLOBS["SSO"],
        "optimize_params": ["borrow_alpha", "borrow_beta", "cost_annual"],
        "bounds": {
            "borrow_alpha": (0.80, 1.50),
            "borrow_beta": (0.0000, 0.0300),
            "cost_annual": (0.0080, 0.0500),
        },
        "initial": {
            "borrow_alpha": SIMULATION_SPECS["SSO"]["borrow_alpha"],
            "borrow_beta": SIMULATION_SPECS["SSO"]["borrow_beta"],
            "cost_annual": SIMULATION_SPECS["SSO"]["cost_annual"],
        },
    },
    "TQQQ": {
        "actual_glob": ACTUAL_ETF_FILE_GLOBS["TQQQ"],
        "optimize_params": ["borrow_alpha", "borrow_beta", "cost_annual", "carry_annual"],
        "bounds": {
            "borrow_alpha": (0.50, 1.75),
            "borrow_beta": (0.0010, 0.0300),
            "cost_annual": (0.0097, 0.0300),
            "carry_annual": (-0.0200, 0.0500),
        },
        "initial": {
            "borrow_alpha": max(1.00, SIMULATION_SPECS["TQQQ"]["borrow_alpha"]),
            "borrow_beta": max(0.0010, SIMULATION_SPECS["TQQQ"]["borrow_beta"]),
            "cost_annual": max(0.0097, SIMULATION_SPECS["TQQQ"]["cost_annual"]),
            "carry_annual": SIMULATION_SPECS["TQQQ"]["carry_annual"],
        },
    },
    "QLD": {
        "actual_glob": ACTUAL_ETF_FILE_GLOBS["QLD"],
        "optimize_params": ["borrow_alpha", "borrow_beta", "cost_annual", "carry_annual"],
        "bounds": {
            "borrow_alpha": (0.50, 1.75),
            "borrow_beta": (0.0010, 0.0300),
            "cost_annual": (0.0098, 0.0300),
            "carry_annual": (-0.0200, 0.0500),
        },
        "initial": {
            "borrow_alpha": max(1.00, SIMULATION_SPECS["QLD"]["borrow_alpha"]),
            "borrow_beta": max(0.0010, SIMULATION_SPECS["QLD"]["borrow_beta"]),
            "cost_annual": max(0.0098, SIMULATION_SPECS["QLD"]["cost_annual"]),
            "carry_annual": SIMULATION_SPECS["QLD"]["carry_annual"],
        },
    },
}
# ---------------------------------------------------------------------------
# Hard floors used during optimization
# ---------------------------------------------------------------------------
# These floors are applied in addition to the optimization bounds.
# They prevent obviously unrealistic solutions such as:
# - borrow_beta = 0.0
# - cost_annual below the chosen ETF expense-ratio floor
#
# Note:
# - TQQQ official gross expense ratio is 0.97%.
# - QLD official gross expense ratio is currently 0.97% on the ProShares
#   fact sheet, but if you want to enforce 0.98% as your research floor,
#   keep 0.0098 below.
OPTIMIZATION_HARD_FLOORS = {
    "SPXL": {
        "cost_annual": 0.0087,
        "borrow_beta": 0.0001,
    },
    "SSO": {
        "cost_annual": 0.0087,
        "borrow_beta": 0.0001,
    },
    "TQQQ": {
        "cost_annual": 0.0097,   # 0.97%
        "borrow_beta": 0.0010,   # 0.10%/yr minimum positive spread
    },
    "QLD": {
        "cost_annual": 0.0098,   # 0.98% floor requested by user
        "borrow_beta": 0.0010,   # 0.10%/yr minimum positive spread
    },
}


# ---------------------------------------------------------------------------
# DCA settings
# ---------------------------------------------------------------------------
# 'every_period' | 'weekly' | 'monthly' | 'quarterly' | 'yearly'
DCA_INTERVAL = "monthly"

# ---------------------------------------------------------------------------
# CASH pseudo-asset settings
# ---------------------------------------------------------------------------

# 'flat'  : 常に0%（Price=1の等価）
# 'fixed' : 年率固定（期毎に等分換算）
# 'rf'    : リスクフリー（月次RFが data/raw に必要）
CASH_MODE = "flat"

# ---------------------------------------------------------------------------
# Tax on rebalancing events
# ---------------------------------------------------------------------------
# Annualized tax rate applied to *realized gains* created by rebalancing trades.
# - Applied only when rebalancing occurs (see REBALANCE_FREQ).
# - 0.00 means no tax drag from rebalancing (default).
# - This is a simple, uniform rate intended for comparative analysis.
# TAX_RATE = 0.0
TAX_RATE = 0.20315  # Japan tax rate

# --- Performance defaults (CLI > settings) ---
# Engine for rolling metrics math: 'auto' | 'numpy' | 'cupy' | 'numba'
PERF_ENGINE = "auto"
# Default worker processes for ProcessPoolExecutor
PERF_WORKERS = 4
# Soft memory cap (GB) to adapt batch size & sample caps; 0 disables adaptation
PERF_MAX_RAM_GB = 10.0
# Batch size for streamed path-extrema computation
PERF_BATCH_SIZE = 256
# Whether to skip plotting by default (can be overridden with --plots)
PERF_NO_PLOTS = False
